# Generated by Django 6.1 on 2026-08-14 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=120)),
                ('property_type', models.CharField(max_length=60)),
                ('area_sqft', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('balconies', models.IntegerField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('total_floors', models.IntegerField(default=1)),
                ('property_age', models.IntegerField(default=0)),
                ('furnished', models.CharField(max_length=60)),
                ('parking', models.IntegerField(default=1)),
                ('facing', models.CharField(max_length=60)),
                ('water_supply', models.CharField(max_length=60)),
                ('lift', models.CharField(default='No', max_length=10)),
                ('power_backup', models.CharField(default='No', max_length=10)),
                ('security', models.CharField(default='No', max_length=10)),
                ('gym', models.CharField(default='No', max_length=10)),
                ('swimming_pool', models.CharField(default='No', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_metro_km', models.FloatField(blank=True, null=True)),
                ('distance_school_km', models.FloatField(blank=True, null=True)),
                ('distance_hospital_km', models.FloatField(blank=True, null=True)),
                ('predicted_price_lakhs', models.FloatField()),
                ('predicted_price_inr', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_instances', to='predictor.prediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'prediction')},
            },
        ),
    ]
