# Generated by Django 6.1 on 2026-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_prediction_is_starred'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityPriceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=120, unique=True)),
                ('avg_price_sqft', models.IntegerField()),
                ('min_price_sqft', models.IntegerField(blank=True, null=True)),
                ('max_price_sqft', models.IntegerField(blank=True, null=True)),
                ('yoy_growth', models.FloatField(help_text='Year over Year growth in %')),
                ('market_demand', models.CharField(help_text='e.g. Very High, High, Moderate', max_length=60)),
                ('segment', models.CharField(help_text='e.g. Ultra Luxury, IT Corridor, Residential', max_length=100)),
                ('period', models.CharField(default='H1 2026', max_length=60)),
                ('source', models.CharField(default='Knight Frank & Hyderabad Market Reports', max_length=120)),
                ('display_order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'locality'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='savedproperty',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='savedproperty',
            name='notes',
        ),
    ]
