# Generated by Django 6.1 on 2026-08-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_localitypriceinsight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitypriceinsight',
            name='historical_data_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='localitypriceinsight',
            name='region',
            field=models.CharField(default='West Hyderabad', max_length=100),
        ),
    ]
